{
    "name": "MOI DcService Meeting",
    "version": "12.0.3",
    "author": "Betimes Solutions Co., Ltd.",
    "website": "https://www.betimes.biz",
    'images': ['static/description/meeting.png'],
    'depends': ['web', 'base', 'calendar', 'project', 'board', 'uom', 'mail'],
    'data': [
        'security/ir.model.access.csv',

        'views/main_menus.xml',
        'views/mt_room_view.xml',
        'views/mt_type_vote_view.xml',
        'views/mt_equipment_view.xml',
        'views/mt_service_view.xml',
        'views/mt_agenda_view.xml',
        'views/mt_type_meeting_view.xml',
        'views/custom_project_project_view.xml',
        'views/mt_room_type_view.xml',
        'views/custom_meeting_view.xml',
        'views/confirm_meeting_list_view.xml',
        'views/mt_board_list_view.xml',
        'views/mt_pos_work_view.xml',
        'views/meeting_view.xml',
        'views/custom_res_partner_view.xml',
        # 'views/custom_res_user_view.xml',
        'views/project_task_view.xml',
        'views/mdm_position_view.xml',
        'views/mt_work_group_view.xml',
        'views/attendee_vote_choice_view.xml',
        'views/mt_system.xml',
        'data/mail_template.xml',
        'views/meeting_notify_view.xml',
        'views/mdm_organize_vew.xml'

    ],
    'demo': [''],
    "application": True,
    'installable': True,
    'auto_install': False,
    "external_dependencies": {"python": ['qrcode'], "bin": []},
}
